project_id = "volhgtspbvgxavqgueqc"

[functions.a100-proxy]
verify_jwt = false

[functions.azure-upload]
verify_jwt = false

[functions.microservices-proxy]
verify_jwt = false

[functions.azure-get-sas]
verify_jwt = false
