project_id = "volhgtspbvgxavqgueqc"

[functions.a100-proxy]
verify_jwt = false

[functions.azure-upload]
verify_jwt = false

[functions.microservices-proxy]
verify_jwt = false

[functions.azure-get-sas]
verify_jwt = false

[functions.azure-fetch-image]
verify_jwt = false

[functions.jewelry-generate]
verify_jwt = false

[functions.workflow-proxy]
verify_jwt = false

[functions.auth-proxy]
verify_jwt = false
